import '@/styles/globals.css'
import { Playfair_Display, Open_Sans } from 'next/font/google'
import Header from './Components/Header/Header'

const  playfairDisplay =  Playfair_Display({subsets: ['latin'], weight: ['400','600', '700', '800'],style: ['normal', 'italic'], variable: "--playfairDisplay-font"})
const  openSans = Open_Sans({subsets: ['latin'], weight: ['400', '500', '600', '700', '800'],style: ['normal', 'italic'], variable: "--openSans-font"})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='touch-none'>
        <body className={`${playfairDisplay.variable} ${openSans.variable} touch-none`}>
            <Header/>
            {children}
        </body>
    </html>
  )
}
